"""
memory.py — AVA Memory (fachada de compatibilidade).

ANTES: este arquivo era um monólito de ~5.500 linhas. AGORA: a implementação
vive em módulos irmãos `memory_*.py` e este arquivo apenas reexporta tudo —
`import memory as mem` (memory_rest_api.py, MCP server) continua funcionando
EXATAMENTE como antes, sem nenhuma mudança de imports ou de comportamento.

Mapa dos módulos:

    memory_config.py      Constantes de tuning, paths, logger `log`
    memory_models.py      Modelos Pydantic (request/response) + MemoryToolError
    memory_engines.py     EmbeddingEngine (E5) e RerankEngine (cross-encoder)
    memory_graph.py       EdgeGraphMixin, Personalized PageRank, expansão de grafo
    memory_db.py          MemoryDB, ShortTermDB, IndexedFilesDB, VisualDictDB,
                          FaceDictDB, VoiceDictDB, ToolsDB (SQLite puro)
    memory_vector.py      LanceStore, MemoryIndex (LanceDB) e _chunk_text
    memory_state.py       AppState/singleton `state`, jobs em background,
                          startup()/shutdown(), integração VectorStore (KG-RAG)
    memory_search.py      Estratégias de busca, segmentação de query, PPR spread,
                          MMR (inibição lateral), builders de MemoryEntry
    memory_ops_memory.py  Handlers: write, write_batch, read, read_st,
                          write_st, clear_session
    memory_ops_files.py   Handlers: indexed_file_*
    memory_ops_dicts.py   Handlers: visual_dict_*, face_dict_*, voice_dict_*
    memory_ops_tools.py   Handlers: tools_*
    memory_status.py      Handler: status

Regras de ouro:
  * Nenhum módulo memory_* importa `memory` (a fachada) — sem ciclos.
  * Dependência só "para baixo": ops → search/state → db/graph/vector →
    models/engines → config.
"""

# Submódulos importados explicitamente: ficam acessíveis como atributos
# da fachada (ex.: memory.memory_search.state) para depuração/patches.
import memory_config, memory_models, memory_engines, memory_graph, memory_db, memory_vector, memory_state, memory_search, memory_ops_memory, memory_ops_files, memory_ops_dicts, memory_ops_tools, memory_status  # noqa: F401

from memory_config import *  # noqa: F401,F403
from memory_models import *  # noqa: F401,F403
from memory_engines import *  # noqa: F401,F403
from memory_graph import *  # noqa: F401,F403
from memory_db import *  # noqa: F401,F403
from memory_vector import *  # noqa: F401,F403
from memory_state import *  # noqa: F401,F403
from memory_search import *  # noqa: F401,F403
from memory_ops_memory import *  # noqa: F401,F403
from memory_ops_files import *  # noqa: F401,F403
from memory_ops_dicts import *  # noqa: F401,F403
from memory_ops_tools import *  # noqa: F401,F403
from memory_status import *  # noqa: F401,F403

__all__ = [
    'ACTIVATION_LOG_MAX_IDS',
    'ACTIVATION_LOG_PATH',
    'AppState',
    'CHUNK_OVERLAP',
    'CHUNK_SIZE',
    'CONTEXT_MAX_CHARS',
    'CONTEXT_TURNS_FETCH',
    'DB_PATH',
    'DECAY_HALF_LIFE_DAYS',
    'DECAY_JOB_INTERVAL_S',
    'DEDUP_THRESHOLD',
    'DICT_GRAPH_MAX_RELATED',
    'DUAL_CONTEXT_WEIGHT',
    'EDGE_CONTRADICTS',
    'EDGE_CO_ACTIVATION',
    'EDGE_DECAY_HALF_LIFE_DAYS',
    'EDGE_DIRECTED_TYPES',
    'EDGE_EXPLICIT_LINK_WEIGHT',
    'EDGE_EXPLICIT_TYPES',
    'EDGE_LEARNING_RATE',
    'EDGE_MIN_SCORE_TO_LINK',
    'EDGE_MMR_FACTORS',
    'EDGE_PPR_FACTORS',
    'EDGE_PRUNE_THRESHOLD',
    'EDGE_TEMPORAL',
    'EDGE_TYPES',
    'EDGE_TYPES_NO_DECAY',
    'EDGE_UPDATES',
    'EMBED_DIM',
    'EMBED_PASSAGE_PREFIX',
    'EMBED_QUERY_PREFIX',
    'EdgeGraphMixin',
    'EmbeddingEngine',
    'FAISS_ID_MAP_PATH',
    'FAISS_INDEX_PATH',
    'FD_AMBIGUOUS_MARGIN',
    'FD_DB_PATH',
    'FD_EMBED_DIM',
    'FD_FAISS_ID_MAP_PATH',
    'FD_FAISS_INDEX_PATH',
    'FD_MIN_SCORE',
    'FD_TOP_K',
    'FaceCandidate',
    'FaceDictDB',
    'FaceDictEntry',
    'FaceDictReadRequest',
    'FaceDictReadResponse',
    'FaceDictUpdateRequest',
    'FaceDictWriteRequest',
    'FaceDictWriteResponse',
    'HEBBIAN_LINK_MAX_IDS',
    'IF_DB_PATH',
    'IF_EMBED_BATCH_SIZE',
    'IF_FAISS_ID_MAP_PATH',
    'IF_FAISS_INDEX_PATH',
    'IF_MAX_CHUNKS',
    'IF_MAX_CONTENT_SIZE',
    'IF_MIN_SCORE',
    'IF_MIN_SCORE_READ',
    'INDEX_FLUSH_INTERVAL_S',
    'IndexedFileCheckResponse',
    'IndexedFileEntry',
    'IndexedFileReadRequest',
    'IndexedFileReadResponse',
    'IndexedFileWriteRequest',
    'IndexedFileWriteResponse',
    'IndexedFilesDB',
    'LANCE_DIR',
    'LANCE_TABLE_PREFIX',
    'LTP_ACCESS_BOOST',
    'LanceStore',
    'MMR_COSINE_FLOOR',
    'MMR_LAMBDA',
    'MT_FACE_DICT',
    'MT_INDEXED_FILE',
    'MT_LONG_TERM',
    'MT_SHORT_TERM',
    'MT_TOOL',
    'MT_VISUAL_DICT',
    'MT_VOICE_DICT',
    'MemoryDB',
    'MemoryEntry',
    'MemoryIndex',
    'MemoryToolError',
    'ONNX_SERVING_URL',
    'PPR_CONVERGENCE_EPS',
    'PPR_DAMPING',
    'PPR_EXPAND_MAX_NODES',
    'PPR_EXPAND_MIN_PATH_WEIGHT',
    'PPR_MAX_ITER',
    'PPR_MIN_ACTIVATION_REINFORCE',
    'PPR_MIN_NEIGHBORS_PER_HOP',
    'PPR_SPREAD_WEIGHT',
    'QUERY_AMBIGUOUS_RATIO',
    'QUERY_SHORT_WORDS',
    'READ_IF_MAX_CHARS',
    'READ_LT_MAX_CHARS',
    'READ_MIN_SCORE',
    'READ_MIN_SCORE_STRICT',
    'READ_ST_MAX_CHARS',
    'READ_TOP_K_FINAL',
    'READ_TOTAL_MAX_CHARS',
    'READ_VS_MAX_CHARS',
    'RERANK_DUPLICATE_SCORE',
    'RERANK_UPDATE_SCORE',
    'ReadRequest',
    'ReadResponse',
    'ReadSTRequest',
    'ReadSTResponse',
    'RelatedMemory',
    'RerankEngine',
    'SEGMENT_MAX_COUNT',
    'SEGMENT_MIN_WORDS',
    'SEGMENT_TRIGGER_WORDS',
    'ST_CLEANUP_INTERVAL_S',
    'ST_DB_PATH',
    'ST_FAISS_ID_MAP_PATH',
    'ST_FAISS_INDEX_PATH',
    'ST_READ_DEFAULT_PAIRS',
    'ST_TTL_HOURS',
    'ShortTermDB',
    'TOOLS_DB_PATH',
    'TOOLS_FALLBACK_TOP_K',
    'TOOLS_LEARN_DEDUP_SCORE',
    'TOOLS_LOW_CONFIDENCE_SCORE',
    'TOOLS_MAX_EXAMPLES',
    'TOOLS_MAX_LEARNED_EXAMPLES',
    'TOOLS_MAX_RELATED',
    'TOOLS_MIN_SCORE',
    'TOOLS_TOP_K',
    'TOOLS_USAGE_MAX_SEQUENCE',
    'TOP_K_READ',
    'ToolMatch',
    'ToolRegisterBatchRequest',
    'ToolRegisterBatchResponse',
    'ToolRegisterRequest',
    'ToolRegisterResponse',
    'ToolSelectRequest',
    'ToolSelectResponse',
    'ToolUsageRequest',
    'ToolsDB',
    'Turn',
    'UPDATE_SIM_THRESHOLD',
    'VD_AMBIGUOUS_MARGIN',
    'VD_DB_PATH',
    'VD_EMBED_DIM',
    'VD_FAISS_ID_MAP_PATH',
    'VD_FAISS_INDEX_PATH',
    'VD_MIN_SCORE',
    'VD_TOP_K',
    'VO_AMBIGUOUS_MARGIN',
    'VO_DB_PATH',
    'VO_EMBED_DIM',
    'VO_FAISS_ID_MAP_PATH',
    'VO_FAISS_INDEX_PATH',
    'VO_MIN_SCORE',
    'VO_TOP_K',
    'VS_DB_PATH',
    'VS_FAISS_ID_MAP_PATH',
    'VS_FAISS_INDEX_PATH',
    'VS_MIN_SCORE',
    'VisualDictCandidate',
    'VisualDictDB',
    'VisualDictEntry',
    'VisualDictReadRequest',
    'VisualDictReadResponse',
    'VisualDictWriteRequest',
    'VisualDictWriteResponse',
    'VoiceCandidate',
    'VoiceDictDB',
    'VoiceDictEntry',
    'VoiceDictReadRequest',
    'VoiceDictReadResponse',
    'VoiceDictUpdateRequest',
    'VoiceDictWriteRequest',
    'VoiceDictWriteResponse',
    'WriteBatchRequest',
    'WriteBatchResponse',
    'WriteRequest',
    'WriteResponse',
    'WriteSTRequest',
    'WriteSTResponse',
    '_GERUND_BOUNDARY_RE',
    '_PURPOSE_BOUNDARY_RE',
    '_STOP_WORDS',
    '_all_indices',
    '_apply_token_budget',
    '_build_adjacency',
    '_build_context_block',
    '_build_if_entries',
    '_build_lt_entries',
    '_build_st_entries',
    '_build_vs_entries',
    '_chunk_text',
    '_classify_query',
    '_delete_tool_row',
    '_dict_graph_related',
    '_edge_key',
    '_edge_traversal_weights',
    '_expand_graph_sync',
    '_fd_write_lock',
    '_fuse_max',
    '_fuse_scores',
    '_gather_status_sync',
    '_hebbian_link_task',
    '_lateral_inhibition_filter',
    '_link_new_memory',
    '_log_activation_sync',
    '_lt_write_lock',
    '_ppr_reinforce_task',
    '_ppr_spread',
    '_ppr_spread_on',
    '_process_write_request',
    '_record_tool_edges_sync',
    '_register_tool_locked',
    '_resolve_vs_paths',
    '_search_dual',
    '_search_expanded',
    '_search_segmented',
    '_split_query_segments',
    '_st_write_lock',
    '_store_long_term_text',
    '_tl_write_lock',
    '_tool_doc_text',
    '_truncate_text',
    '_upsert_edges_sync',
    '_vd_write_lock',
    '_vo_write_lock',
    'clear_session',
    'decay_job',
    'face_dict_delete',
    'face_dict_get',
    'face_dict_list',
    'face_dict_read',
    'face_dict_update',
    'face_dict_write',
    'get_chunk_by_id',
    'index_flush_job',
    'indexed_file_check',
    'indexed_file_delete',
    'indexed_file_delete_by_path',
    'indexed_file_get',
    'indexed_file_list',
    'indexed_file_read',
    'indexed_file_write',
    'log',
    'personalized_pagerank',
    'read_memory',
    'read_short_term',
    'shutdown',
    'st_cleanup_job',
    'startup',
    'state',
    'status',
    'tools_delete',
    'tools_list',
    'tools_record_usage',
    'tools_register',
    'tools_register_batch',
    'tools_select',
    'visual_dict_delete',
    'visual_dict_get',
    'visual_dict_list',
    'visual_dict_read',
    'visual_dict_write',
    'voice_dict_delete',
    'voice_dict_get',
    'voice_dict_list',
    'voice_dict_read',
    'voice_dict_update',
    'voice_dict_write',
    'write_memory',
    'write_memory_batch',
    'write_short_term',
]
